language: node_js
node_js:
  - "11"
  - "12"
addons:
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run test
  - travis_wait 10
sudo: true
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
