anguage: node_js
node_js:
  - "11"
  - "12"
addons:
  chrome: stable
cache:
  directories:
    - node_modules
scripts:
  - travis_wait 90 make install
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
